name: wordpress
version: 0.8.14
appVersion: 4.9.4
description: Web publishing platform for building blogs and websites.
keywords:
- wordpress
- cms
- blog
- http
- web
- application
- php
home: http://www.wordpress.com/

maintainers:
- name: ishujeetpanjeta@gmail.com
  email: ishujeetpanjeta@gmail.com
engine: gotpl
