name: mariadb
version: 2.1.11
appVersion: 10.1.31
description: Fast, reliable, scalable, and easy to use open-source relational database system. MariaDB Server is intended for mission-critical, heavy-load production systems as well as for embedding into mass-deployed software.
keywords:
- mariadb
- mysql
- database
- sql
- prometheus
home: https://mariadb.org
maintainers:
- name: Ishujeet
  email: ishujeetpanjeta@gmail.com
engine: gotpl
